I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/initialization/place.entity.rpy", line 1, in script
    init python:
  File "game/scripts/initialization/place.entity.rpy", line 1, in script
    init python:
  File "game/scripts/initialization/place.entity.rpy", line 22, in <module>
    Locations.append(Place("Banco","banco",False))
NameError: name 'Place' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/scripts/initialization/place.entity.rpy", line 1, in script
    init python:
  File "game/scripts/initialization/place.entity.rpy", line 1, in script
    init python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/initialization/place.entity.rpy", line 22, in <module>
    Locations.append(Place("Banco","banco",False))
NameError: name 'Place' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
projeto teste 2 1.0
Mon Jun 27 00:05:21 2022
